# Generated by Django 5.2.7 on 2025-10-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getintouch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phon_number',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='service',
            field=models.CharField(choices=[('General', 'General'), ('Website Development', 'Website Development'), ('Mentorship', 'Mentorship')], default='General', max_length=50),
        ),
    ]
