# Generated by Django 5.2.7 on 2025-10-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getintouch', '0002_rename_phon_number_contact_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.CharField(choices=[('General', 'General'), ('Website Development', 'Website Development'), ('Mentor ship', 'Mentor ship')], default='General', max_length=50),
        ),
    ]
