# Generated by Django 5.2.7 on 2025-10-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getintouch', '0003_alter_contact_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.CharField(choices=[('General', 'General'), ('Website Development', 'Website Development'), ('Mentorship', 'Mentorship')], default='General', max_length=50),
        ),
    ]
