# Generated by Django 5.2.7 on 2025-10-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getintouch', '0004_alter_contact_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
