# Generated by Django 5.2.7 on 2025-10-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getintouch', '0005_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
